import os
import glob
from pathlib import Path
from datetime import datetime

def generate_index_html(reports_dir="reports", output_dir="public"):
    """
    Scans for markdown reports and generates a static index.html
    """
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Get all markdown files
    md_files = glob.glob(os.path.join(reports_dir, "*.md"))
    md_files.sort(key=os.path.getmtime, reverse=True)
    
    # Basic HTML Template
    html_content = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Analysis Reports</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; background-color: #f6f8fa; }
        h1 { color: #24292e; border-bottom: 1px solid #eaecef; padding-bottom: 10px; }
        .report-list { list-style: none; padding: 0; }
        .report-item { background: white; border: 1px solid #e1e4e8; border-radius: 6px; margin-bottom: 10px; padding: 16px; transition: box-shadow 0.2s; }
        .report-item:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
        .report-link { font-size: 18px; font-weight: 600; color: #0366d6; text-decoration: none; display: block; margin-bottom: 5px; }
        .report-link:hover { text-decoration: underline; }
        .report-meta { font-size: 12px; color: #586069; }
        footer { margin-top: 40px; text-align: center; font-size: 12px; color: #6a737d; }
    </style>
</head>
<body>
    <h1>📈 A股每日分析报告</h1>
    <ul class="report-list">
"""

    if not md_files:
        html_content += """
        <li class="report-item">
            <div class="report-meta">暂无报告生成</div>
        </li>
        """
    
    for file_path in md_files:
        filename = os.path.basename(file_path)
        # We will copy md files to public dir, so link is just filename
        link = filename
        
        # Get basic info
        stat = os.stat(file_path)
        mod_time = datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
        
        size_kb = stat.st_size / 1024
        
        html_content += f"""
        <li class="report-item">
            <a href="{link}" class="report-link">{filename}</a>
            <div class="report-meta">生成时间: {mod_time} | 大小: {size_kb:.1f} KB</div>
        </li>
        """

    html_content += """
    </ul>
    <footer>
        Generated by Stock Analysis System
    </footer>
</body>
</html>
"""
    
    # Write index.html
    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(f"Generated index.html with {len(md_files)} reports.")

    # Copy markdown files to public dir
    import shutil
    for file_path in md_files:
        shutil.copy2(file_path, output_dir)
        print(f"Copied {file_path} to {output_dir}")

if __name__ == "__main__":
    generate_index_html()
